### ISSUE TITLE
Example behaves unexpectedly, adds entire input on each key stroke

### ISSUE THREAD

**Issue by QuarkNerd** [thejpster/menu#7]
Using 
```
menu = "0.3.2"
pancurses = "0.16.1"
```
win 10, `cargo run` run in Git BASH.

I copied the example and it behaves like so

cmd

```
>
```

I press a 

```
>> a
```

I press b

```
>> > ab
```

I press c

```
>> > a> abc
```

**Comment by thejpster** [comment]
It appears your terminal doesn't understand "\r" as "go back to start of line"

**Comment by huntc** [comment]
Is this one now ok to close given that it should be reasonable for a terminal to process return?
